### ISSUE TITLE
Error message when executing BasicRouting example

### ISSUE THREAD

**Issue by restelli** [clavin-xlnx/RapidWright-binder#1]
I encounter the following error (Null pointer exception) when running the first cell of the example exercise [BasicRouting.ipynb](https://github.com/clavin-xlnx/RapidWright-binder/blob/master/BasicRouting.ipynb):
```
src = DesignTools.createPinAndAddToNet(src_ff,"Q",net)
	at com.xilinx.rapidwright.design.DesignTools.createPinAndAddToNet(DesignTools.java:543)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)

java.lang.NullPointerException: java.lang.NullPointerException
```
The error is present both when I run the cell in the provided binder (JRE-8)  and when I run it on my machine (JRE-11)
I am using the following stand alone RapidWright jar: rapidwright-2018.3.2-standalone-lin64.jar

Thanks in advance for your reply, and thanks for posting this type of tutorials: they are a fantastic complement to the documentation.

**Comment by restelli** [comment]
Update.
The error goes away if I install RapidWright using rapidwright-installer.jar and create the jupyter kernel using the command
```
java com.xilinx.rapidwright.util.RapidWright --create_jupyter_kernel
```

**Comment by seifoorisara** [comment]
Hi,
I want to use RapidWright in UBUNTU 18.04.
I run these instructions but encounter the following errors:
What can I do?


java com.xilinx.rapidwright.util.RapidWright --create_jupyter_kernel
Wrote Jupyter Notebook Kernel File: '/home/user/jython27/kernel.json'

You can install the RapidWright (Jython 2.7) kernel by running:
    $ jupyter kernelspec install /home/user/jython27
and list currently installed kernels with:
    $ jupyter kernelspec list
(base) user@parsapc1000:~$ sudo jupyter kernelspec install /home/user/jython27
[sudo] password for user: 
Error executing Jupyter command 'kernelspec': [Errno 2] No such file or directory

**Comment by seifoorisara** [comment]
Can any body help me? I spend a lot of time to correct this issue but it did not solved.

**Comment by restelli** [comment]
seifoorisara, have you checked if the folder jython27 has been written on the path /home/user/jython27 ?
